# Extract of the config.yaml from the main hamstring repository.
logging:
  base:
    debug: false

pipeline:
  zeek:
    sensors:
      zeek1:
        static_analysis: true
        protocols:
          - dns
          - http
        interfaces:
          - eth0

environment:
  kafka_brokers:
    - external_port: 8098
      node_ip: 127.0.0.1
  kafka_topics_prefix:
    pipeline:
      logserver_in: "hamstring_input"
